<a href="https://colab.research.google.com/github/Siu0901/AI_study/blob/main/%EC%BC%80%EB%9D%BC%EC%8A%A4%EC%9D%98_SimpleRNN%EA%B3%BC_LSTM_%EC%9D%B4%ED%95%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN, LSTM, Bidirectional

In [2]:
train_X = [[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]
print(np.shape(train_X))

(4, 5)


In [3]:
train_X = [[[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]]
train_X = np.array(train_X, dtype=np.float32)
print(train_X.shape)

(1, 4, 5)


In [9]:
# SimpleRNN 이해

In [10]:
# 기본적으로 return_sequences가 False인 경우에는 SimpleRNN은
# 마지막 시점의 은닉 상태만 출력

rnn = SimpleRNN(3) # 은닉 상태 크기 3으로 지정
# rnn = SimpleRNN(3, return_sequences=False, return_state=False)와 동일.
hidden_state = rnn(train_X)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))

hidden state : [[ 0.3230485   0.4777671  -0.99173236]], shape: (1, 3)


In [11]:
# 모든 시점 출력
rnn = SimpleRNN(3, return_sequences=True)
hidden_states = rnn(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))

hidden states : [[[-0.71816957 -0.17317982  0.86934644]
  [-0.6503197   0.874568    0.17890233]
  [ 0.67456275  0.17101407  0.84770554]
  [-0.6775691  -0.10959201  0.92477494]]], shape: (1, 4, 3)


In [12]:
# 모든 시점과 마지막 시점의 은닉상태를 출력

rnn = SimpleRNN(3, return_sequences=True, return_state=True)
hidden_states, last_state = rnn(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))

hidden states : [[[-0.730924    0.9867087   0.977723  ]
  [-0.9784584   0.9934442   0.18734208]
  [-0.9981031   0.93055564  0.84021485]
  [-0.9966289   0.3423102   0.00100422]]], shape: (1, 4, 3)
last hidden state : [[-0.9966289   0.3423102   0.00100422]], shape: (1, 3)


In [13]:
# LSTM 이해

In [14]:
lstm = LSTM(3, return_sequences=False, return_state=True)
hidden_state, last_state, last_cell_state = lstm(train_X)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))
print('last cell state : {}, shape: {}'.format(last_cell_state, last_cell_state.shape))

hidden state : [[ 0.3420489  -0.15784515 -0.30237332]], shape: (1, 3)
last hidden state : [[ 0.3420489  -0.15784515 -0.30237332]], shape: (1, 3)
last cell state : [[ 1.3113664  -0.77153045 -0.6084672 ]], shape: (1, 3)
